name: 'Label Pull Requests'
description: 'Label pull requests by files altered'
author: 'aktions'
inputs: 
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
